[tool.black]
line-length = 88
target-version = ['py38']
skip-string-normalization = true
exclude = '''
/(
    .git
    .tox
    .nox
    .venv
    .hypothesis
    .mypy_cache
    .pytest_cache
    dist
    build
)/
'''

[tool.flake8]
max-line-length = 88
exclude =
    .git
    .tox
    .nox
    .venv
    .hypothesis
    .mypy_cache
    .pytest_cache
    dist
    build
    migrations
    setup.py
    config.py

[tool.isort]
profile = "black"
line_length = 88
known_third_party = ["numpy", "torch", "jax", "onnx", "pycuda"]
known_first_party = ["zwgrad"]
skip = ["migrations", "tests"]
src_paths = ["src"]

[tool.mypy]
files = "src"
ignore_missing_imports = true
disallow_untyped_calls = true
disallow_untyped_defs = true
check_untyped_defs = true
warn_unused_ignores = true

[tool.pylint]
max-line-length = 88
disable = "C0114,C0115,C0116"  # Disable docstring required warnings
